batch_size: 256
d_model: 100
dim_feedforward: 512
dropout: 0.1
in_size: 100
learning_rate: 0.0001
max_length: 100
nhead: 10
num_layers: 8
out_size: 25
partition:
- 25
- 4
- 4
reduction: null
step: 25
